// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVUzRTU-EBlZcN43-FzWVQc-L7rhJzIA',
    appId: '1:552806970314:web:3e765feb650fa7a811d533',
    messagingSenderId: '552806970314',
    projectId: 'ca-quizz-104ab',
    authDomain: 'ca-quizz-104ab.firebaseapp.com',
    storageBucket: 'ca-quizz-104ab.firebasestorage.app',
    measurementId: 'G-E1VC1RR529',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHS-YLc0gB1AIt7s6KBmMrd387ICmHxI',
    appId: '1:552806970314:android:5534f6f8c32f6a6811d533',
    messagingSenderId: '552806970314',
    projectId: 'ca-quizz-104ab',
    storageBucket: 'ca-quizz-104ab.firebasestorage.app',
  );
}
